In [1]:
import numpy as mat
mat1=mat.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=mat.array([[7,8,9],[1,2,3],[4,5,6]])
sum=mat1+mat2
print("First Matrix :\n",mat1)
print("Second Matrix :\n",mat2)
print("Sum Matrix : \n",sum)

First Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix :
 [[7 8 9]
 [1 2 3]
 [4 5 6]]
Sum Matrix : 
 [[ 8 10 12]
 [ 5  7  9]
 [11 13 15]]
