# Largest of 3 numbers

In [86]:
a,b,c=map(int,input("Enter 3 numbers : ").split())
if (a>=b and a>=c):
    l=a
elif(b>=a and b>=c):
    l=b
else:
    l=c
print("The largest number is",l)    

Enter 3 numbers : 80 90 10
The largest number is 90


# Multiplication Table

In [14]:
n=int(input("Enter the number to find the table : "))
for i in range (1,11):
    print(f"{i}*{n}={i*n}")

Enter the number to find the table : 5
1*5=5
2*5=10
3*5=15
4*5=20
5*5=25
6*5=30
7*5=35
8*5=40
9*5=45
10*5=50


# Volume and Surface Area of a Cylinder

In [33]:
import numpy
def VolArea(r,h):
    sa=(2*pi*r*h)
    vol=(pi*r*r*h)
    tsa=sa+(2*pi*r*r)
    return sa,tsa,vol
r=int(input("Enter the radius of the cylinder : "))
h=int(input("Enter the height of the cylinder : "))
s,t,v=VolArea(r,h)
print(f"Volume ={v:.2f}\nSurface Area={s:.2f}\nTotal Surface area={t:.2f}")


Enter the radius of the cylinder : 5
Enter the height of the cylinder : 6
Volume =471.24
Surface Area=188.50
Total Surface area=345.58


# Replacing a word

In [47]:
string=input("Enter a sentence : ")
old=input("Enter the word to replace : ")
new=input("Enter the new word : ")
#string.replace(old,new)
word=string.split()
newStr=""
for i in word:
    if old==i:
        newStr=newStr+" "+new
    else:
        newStr=newStr+" "+i
print(newStr)

Enter a sentence : I love to play football
Enter the word to replace : play
Enter the new word : watch
 I love to watch football


# Validity of an Email

In [76]:
valid=True
import string as st
low=st.ascii_lowercase
whole=st.ascii_letters+"_.-"+"1234567890"

email=input("Enter an email")
parts=email.split("@")
userid=parts[0]
domain=parts[1]

for i in userid:
    if i not in whole:
        valid=False
        break
dom=domain.split(".")
for i in dom[0]:
    if i not in low:
        valid=False
        break
if len(dom[1])>2:
    for i in dom[1]:
        if i not in low:
            valid=False
            break
else:
    valid=False
if valid:
    print("The entered mail id is valid")
else:
    print("The entered mail id is not valid")

Enter an emaildtydysdt@ghgfh4.hgg
The entered mail id is not valid


# Remove the occurence of a number

In [93]:
n=int(input("Enter the number of elements : "))
elements=[]
for i in range(n):
    elements.append(int(input(f"Enter the element {i+1} : ")))
x=int(input("Enter the element to be removed : "))
while(x in elements):
    elements.remove(x)
print(elements)

Enter the number of elements : 5
Enter the element 1 : 4
Enter the element 2 : 4
Enter the element 3 : 4
Enter the element 4 : 3
Enter the element 5 : 2
Enter the element to be removed : 4
[3, 2]


# Matrix Addition

In [102]:
import numpy as np
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"First Matrix : \n{mat1}\nSecond Matrix : \n{mat2}\nSum:\n{mat1+mat2}")        

First Matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [23]:
import numpy as np
r,c=map(int,input("Enter the number of rows and columns").split())
mat1=[]
mat2=[]
print("Martix 1\n")
for i in range(r):
    row=[]
    for j in range(c):
        row.append(int(input()))
    mat1.append(row)
print("Martix 2\n")
for i in range(r):
    row=[]
    for j in range(c):
        row.append(int(input()))
    mat2.append(row)
print(f"Sum\n{np.add(mat1,mat2)}")


Enter the number of rows and columns2 2
Martix 1

1
2
3
4
Martix 2

7
8
9
10
Sum 2
[[ 8 10]
 [12 14]]


# Tuple

In [25]:
nums=(1,2,3,4,5,6,7,8,9)
odd=()
even=()
for i in range(len(nums)):
    if nums[i]%2==0:
        even+=(nums[i],)
    else:
        odd+=(nums[i],)
print(f"Original Tuple : {nums}\nOdd Tuple : {odd}\nEven Tuple : {even}")

Original Tuple : (1, 2, 3, 4, 5, 6, 7, 8, 9)
Odd Tuple : (1, 3, 5, 7, 9)
Even Tuple : (2, 4, 6, 8)


# Dictionary

In [37]:
books={'book1':100,'book2':200}
def add(books):
    name=input("Enter the name of the book : ")
    num=int(input("Enter the number of stocks : "))
    books.update({name:num})
def delete(books):
    name=input("Enter the name of the book to delete: ")
    books.pop(name)
print(f"Books : {books}")
op=0
print("1.Add/Update\n2.Delete\n3.Display\n4.Exit")
while(op!=4):
    op=(int(input("Choose an option")))
    if (op==1):
        add(books)
    elif (op==2):
        delete(books)
    elif op==3:
        print(f"Books : {books}")

Books : {'book1': 100, 'book2': 200}
1.Add/Update
2.Delete
3.Display
4.Exit
Choose an option3
Books : {'book1': 100, 'book2': 200}
Choose an option3
Books : {'book1': 100, 'book2': 200}
Choose an option4


In [71]:
f = open("demofile2.txt", "w")
f.write("1,2,3,4,5,6,7,8,9")
f.close()

#open and read the file after the appending:
f = open("demofile2.txt", "r")
l=map(int,f.read().split(","))
# for i in l:
#     if i==0 or i==1:
#         continue
#     for j in range()

ValueError: invalid literal for int() with base 10: ''